version = 0.1

[default.deploy]
stack_name = "20q-fastapi-lambda"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
fail_on_empty_changeset = false
parameter_overrides = [
  "SUPABASE_URL=$SUPABASE_URL",
  "SUPABASE_SERVICE_ROLE_KEY=$SUPABASE_SERVICE_ROLE_KEY",
  "SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY",
  "OPENAI_API_KEY=$OPENAI_API_KEY",
  "ELEVENLABS_API_KEY=$ELEVENLABS_API_KEY",
  "ELEVENLABS_VOICE_ID=$ELEVENLABS_VOICE_ID"
]