AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 20Q FastAPI Lambda (us-west-2)

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    MemorySize: 512

Parameters:
  SUPABASEURL:
    Type: String
  SUPABASESERVICEROLEKEY:
    Type: String
  SUPABASEANONKEY:
    Type: String
  OPENAIAPIKEY:
    Type: String
  ELEVENLABSAPIKEY:
    Type: String
  ELEVENLABSVOICEID:
    Type: String

Resources:
  # API Gateway without Authentication
  WhisperChaseApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS,HEAD,PATCH'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
        MaxAge: "'86400'"

  # Lambda Function
  WhisperChaseFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: WhisperChase
      CodeUri: backend/
      Handler: app.handler
      Runtime: python3.13
      Timeout: 30
      MemorySize: 512
      Environment:
        Variables:
          SUPABASE_URL: !Ref SUPABASEURL
          SUPABASE_SERVICE_ROLE_KEY: !Ref SUPABASESERVICEROLEKEY
          SUPABASE_ANON_KEY: !Ref SUPABASEANONKEY
          OPENAI_API_KEY: !Ref OPENAIAPIKEY
          ELEVENLABS_API_KEY: !Ref ELEVENLABSAPIKEY
          ELEVENLABS_VOICE_ID: !Ref ELEVENLABSVOICEID
      Events:
        RootApi:
          Type: Api
          Properties:
            RestApiId: !Ref WhisperChaseApi
            Path: /
            Method: ANY
        DocsApi:
          Type: Api
          Properties:
            RestApiId: !Ref WhisperChaseApi
            Path: /docs
            Method: ANY
        ProxyApi:
          Type: Api
          Properties:
            RestApiId: !Ref WhisperChaseApi
            Path: /{proxy+}
            Method: ANY


Outputs:
  WhisperChaseApi:
    Description: "API Gateway endpoint URL for Prod stage for WhisperChase function"
    Value: !Sub "https://${WhisperChaseApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  WhisperChaseFunction:
    Description: "WhisperChase Lambda Function ARN"
    Value: !GetAtt WhisperChaseFunction.Arn
  WhisperChaseFunctionIamRole:
    Description: "Implicit IAM Role created for WhisperChase function"
    Value: !GetAtt WhisperChaseFunctionRole.Arn