name: Deploy SAM App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-west-2
      PYTHON_VERSION: '3.13'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install AWS SAM CLI
        run: |
          pip install aws-sam-cli

      - name: Deploy SAM app
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name 20q-fastapi-lambda --capabilities CAPABILITY_IAM --region ${{ env.AWS_REGION }} --parameter-overrides SUPABASE_URL=${{ secrets.SUPABASE_URL }} SUPABASE_SERVICE_ROLE_KEY=${{ secrets.SUPABASE_SERVICE_ROLE_KEY }} SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }} OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} ELEVENLABS_API_KEY=${{ secrets.ELEVENLABS_API_KEY }} ELEVENLABS_VOICE_ID=${{ secrets.ELEVENLABS_VOICE_ID }} 